### ISSUE TITLE
Usage with splitting/chunking ?

### ISSUE THREAD

**Issue by loudwinston** [gaearon/react-transform-boilerplate#26]
How can I get react-transform working with hot module loading when the `entry` field is an object like as required by https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code?

react-transform-boilerplate assumes that the `entry` field will be an array, and that `webpack-hot-middleware/client` will be the first item in it.

**Comment by gaearon** [comment]
You can try doing this:

```
entry: {
  something: ['./src/something', 'webpack-hot-middleware/client'],
  somethingElse: ['./src/somethingElse', 'webpack-hot-middleware/client']
}
```

Does it work?

**Comment by loudwinston** [comment]
So this works for my app's entry point, but not for the vendor chunk.  If I do

```javascript
var VENDOR_DEPENDENCIES = [
    'react',
    'react/addons',
    'q',
    'lodash',
    'immutable',
    'reflux',
    'moment',
    'react-router'
];

var config = {
    entry: {
        app: ['./assets/js/app.js', 'webpack-hot-middleware/client']
        vendor: [VENDOR_DEPENDENCIES, 'webpack-hot-middleware/client']
    }
}
```

I get the following error
```
TypeError: Object react,react/addons,q,lodash,immutable,reflux,moment,react-router has no method 'replace'
    at NormalModuleFactory.<anonymous> (/Users/loudwinston/test-project/node_modules/webpack/lib/NormalModuleFactory.js:70:27)
    at NormalModuleFactory.<anonymous> (/Users/loudwinston/test-project/node_modules/webpack/lib/NormalModuleFactory.js:27:4)
    at NormalModuleFactory.<anonymous> (/Users/loudwinston/test-project/node_modules/webpack/lib/NormalModuleFactory.js:156:3)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/loudwinston/test-project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/Users/loudwinston/test-project/node_modules/webpack/lib/NormalModuleFactory.js:141:7)
    at Compilation.<anonymous> (/Users/loudwinston/test-project/node_modules/webpack/lib/Compilation.js:213:11)
    at /Users/loudwinston/test-project/node_modules/webpack/node_modules/async/lib/async.js:187:20
    at /Users/loudwinston/test-project/node_modules/webpack/node_modules/async/lib/async.js:239:13
    at _arrayEach (/Users/loudwinston/test-project/node_modules/webpack/node_modules/async/lib/async.js:91:13)
    at _each (/Users/loudwinston/test-project/node_modules/webpack/node_modules/async/lib/async.js:82:13)
```

**Comment by loudwinston** [comment]
Okay I got it to work.  I realized that I should just be adding 'webpack-hot-middleware/client' to the `VENDOR_DEPENDENCIES` array directly.  

Thanks for your help!

**Comment by loudwinston** [comment]
Could the documentation / example be updated to include this information?  I'd be happy to submit a PR for this.

There's actually a few things that I've learned while switching my project to use react-transform that I think would be really useful to have in the readme/examples.  Would you mind if I opened another issue to discuss these?

Thanks for your effort on all of these tools!

**Comment by gaearon** [comment]
I wanted this example to be pretty focused on a single thing but I see that people bump into all sorts of issues taking it too literally. Sure, I'm happy to accept PRs.
