### ISSUE TITLE
Implementing devServer page rendering

### ISSUE THREAD

**Issue by cidevant** [gaearon/react-transform-boilerplate#27]
Hello, I am trying to make app, where nodejs renders page on server side, and then it serves to client. 
This example works great, but I am stuck with one problem. 

I am trying to insert my React-Routes to devServer.js and then run Router.
I fail to run``` devServer.js```, because devServer.js is in vanilla JS (```node devServer.js```), BUT! my ```src/my_routes.jsx``` is written in ES6 + JSX. 

I dont know how to tell ```package.json``` to run start task with ```babel``` transformer.

```
"scripts": {
    "start": "node devServer.js",
}
```

I tried ```"start": "babel devServer.js | node"``` but it doesnt work.

**Comment by cidevant** [comment]
```
var Router = require('react-router');
var React  = require('react');
var Routes = require('./src/my_routes');

app.use(function(req, res, next) {
  var router = Router.create({location: req.url, routes: Routes})
  router.run(function(Root, state) {
    var reactHtml = React.renderToString(<Root />),
        indexHtml = path.join(__dirname, 'index.html');
    return res.sendFile(indexHtml)
  })
})
```

ERROR

```
 1  ~/Code/JavaScript/react-builders/webpack-react-dev  master *  >  babel devServer.js | node
/Users/katz/Code/JavaScript/react-builders/webpack-react-dev/src/my_routes.js:1
(function (exports, require, module, __filename, __dirname) { import Router
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [stdin]:11:14
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
```

**Comment by epeli** [comment]
Try

```
"scripts": {
    "start": "babel-node devServer.js",
}
```

**Comment by cidevant** [comment]
Better, but still fails

```
> react-transform-boilerplate@1.0.0 start /Users/katz/Code/JavaScript/react-builders/webpack-react-dev
> babel-node  devServer.js

/Users/katz/Code/JavaScript/react-builders/webpack-react-dev/node_modules/react-transform-hmr/lib/index.js:51
    throw new Error('locals[0] does not appear to be a `module` object with Ho
          ^
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
```

**Comment by cidevant** [comment]
When running ```NODE_ENV=production babel-node  devServer.js``` It fails on 

```
SyntaxError: /Users/katz/Code/JavaScript/react-builders/webpack-react-dev/src/styles/states/home-index.scss: Unexpected token (1:0)
> 1 | .HomeIndex {
    | ^
  2 |   background: #444;
  3 |   color: white;
  4 | }
```

SASS-LOADER doesnt work ??? How to tell babel-to use sass-loader ? Or it is WEBPACK error?

**Comment by gaearon** [comment]
This is an issue unrelated to this boilerplate.

If you use Webpacks's overloading of `require` for styles, you can't expect it to work on Node. Your best option is to compile the backend with Webpack as well (using `target: 'node'`). Again, this is out of scope of this boilerplate so please consult appropriate discussion forums such as StackOverflow.
