### ISSUE TITLE
"Symbol is not defined" error

### ISSUE THREAD

**Issue by seanislegend** [gaearon/react-transform-boilerplate#32]
Hello! Just trying this out. I've followed the steps in the README. But, running the "npm start" command results in this output/error:

```
> react-transform-boilerplate@1.0.0 start /dev/react-transform-boilerplate
> node devServer.js

Listening at http://localhost:3000
webpack built 3ce3db4b60dda21e65d3 in 889ms
Hash: 3ce3db4b60dda21e65d3
Version: webpack 1.12.2
Time: 889ms
    Asset     Size  Chunks       Chunk Names
bundle.js  29.7 kB       0       main
chunk    {0} bundle.js (main) 6.62 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 2.6 kB {0} [built]
    [2] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [3] (webpack)-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
    [4] (webpack)-hot-middleware/client-overlay.js 917 bytes {0} [built]
    [5] (webpack)-hot-middleware/processUpdate.js 2.75 kB {0} [built]

ERROR in ./src/index.js
Module build failed: ReferenceError: /dev/react-transform-boilerplate/src/index.js: Symbol is not defined
    at buildIsCreateClassCallExpression (/dev/react-transform-boilerplate/node_modules/babel-plugin-react-transform/lib/index.js:65:43)
    at NodePath.enter (/dev/react-transform-boilerplate/node_modules/babel-plugin-react-transform/lib/index.js:346:42)
    at NodePath.call (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (/dev/react-transform-boilerplate/node_modules/babel-core/lib/traversal/index.js:55:14)
    at PluginPass.transform (/dev/react-transform-boilerplate/node_modules/babel-core/lib/transformation/plugin-pass.js:51:27)
    at File.transform (/dev/react-transform-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:621:12)
 @ multi main
```

Node version is 0.10.26.

**Comment by gaearon** [comment]
Can I ask you to try `babel-plugin-react-transform@1.1.1`?

**Comment by seanislegend** [comment]
Thanks, @gaearon, that worked! Should the ```package.json``` be updated to reflect this?

**Comment by gaearon** [comment]
Done: https://github.com/gaearon/react-transform-boilerplate/commit/82cb8b7c48498949b28a23057c339a892663d0ac.
Thanks for reporting. :+1:
