### ISSUE TITLE
error after npm start

### ISSUE THREAD

**Issue by Proxiweb** [gaearon/react-transform-boilerplate#5]
Hello, after npm install and npm start, it throws this error : 
```
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 2.55 kB {0} [built]
    [2] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [3] (webpack)-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
    [4] (webpack)-hot-middleware/client-overlay.js 917 bytes {0} [built]
    [5] (webpack)-hot-middleware/processUpdate.js 2.75 kB {0} [built]

ERROR in ./src/index.js
Module build failed: ReferenceError: Symbol is not defined
    at exports.default (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-plugin-react-transform/lib/index.js:36:18)
    at Function.memoisePluginContainer (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-core/lib/transformation/file/plugin-manager.js:77:23)
    at PluginManager.add (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-core/lib/transformation/file/plugin-manager.js:209:30)
    at File.buildTransformers (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/regisg/Projets/react-transform-boilerplate/node_modules/babel-loader/index.js:69:12)

```

**Comment by MoOx** [comment]
You probably use an old version of node that doesn't have `Symbol`.

**Comment by Proxiweb** [comment]
Right, thanks. I was sure to have the last version. Thanks for this boilerplate.

**Comment by gaearon** [comment]
FWIW I removed Symbol usage in `babel-plugin-react-transform@1.0.3` so you should be good even with Node 0.10.
