### ISSUE TITLE
Error when building from cli

### ISSUE THREAD

**Issue by xabikos** [gaearon/react-transform-boilerplate#75]
If you try to create the bundle through webpack cli it fails. More specific after installing the packages if you fire 
`
.\node_modules\.bin\webpack --module-bind jsx=babel --module-bind js=babel --entry ./src/index.js --output-path build --output-filename bundle.js
`
you get a long error back that starts like this and is related to catch errors transform
>ERROR in ./~/react-transform-catch-errors/lib/index.js
module build failed: ReferenceError: [BABEL] C:\Development\react-transform-boilerplate\node_modules\react-transform-catch-errors\lib\index.js: Unknown option: C:\Development\react-transform-boilerplate\node_modules\react-transform-catch-errors\.babelrc.stage
    at Logger.error (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:262:18)

And if we remove that transform and leave only the hmr one we get an error like the following
>ERROR in ./~/react-proxy/modules/index.js
Module build failed: ReferenceError: [BABEL] C:\Development\react-transform-boilerplate\node_modules\react-proxy\modules\index.js: Unknown option: C:\Development\react-transform-boilerplate\node_modules\react-proxy\.babelrc.stage
    at Logger.error (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:262:18)
    at OptionManager.addConfig (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:221:10)
    at OptionManager.findConfigs (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:364:16)
    at OptionManager.init (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\options\option-manager.js:412:12)
    at File.initOptions (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:190:75)
    at new File (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:121:22)
    at Pipeline.transform (C:\Development\react-transform-boilerplate\node_modules\babel-core\lib\transformation\pipeline.js:42:16)
    at transpile (C:\Development\react-transform-boilerplate\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (C:\Development\react-transform-boilerplate\node_modules\babel-loader\index.js:87:14)
 @ ./~/react-transform-hmr/lib/index.js 39:18-40

If from terminal execute just 

`.\node_modules\.bin\webpack  --config webpack.config.dev.js` Everything works fine which is strange. Whatever is possible from configuration should be available from cli too.

**Comment by thejameskyle** [comment]
The error is actually telling you exactly what is happening:

```sh
module build failed:
  ReferenceError: [BABEL] C:\...\node_modules\react-transform-catch-errors\lib\index.js:
  Unknown option: C:\...\node_modules\react-transform-catch-errors.babelrc.stage
```
 
It's picking up the `stage` option from a `.babelrc` file inside `node_modules/react-transform-catch-errors`.

Babel shouldn't be touching `node_modules` at all.

**Comment by thejameskyle** [comment]
Yeah, it looks like `--module-bind` just runs babel on every file with the `jsx` or `js` extension in your example.

Don't do that.
